version: "3.8"

services:
  NetCoreRabbitMQ_Db:
    image: postgres:15
    container_name: NetCoreRabbitMQ_Db
    restart: always
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
  NetCoreRabbitMQ:
    image: rabbitmq:3-management-alpine
    container_name: "NetCoreRabbitMQ"
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
volumes:
  postgres_data:
